version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/cosmos/iavl
    versions:
    - "> 0.15.0-rc5"
  - dependency-name: github.com/tendermint/iavl
    versions:
    - "> 0.13.2"
  - dependency-name: github.com/klauspost/compress
    versions:
    - 1.11.9
  - dependency-name: github.com/libp2p/go-libp2p-core
    versions:
    - 0.8.0
    - 0.8.2
    - 0.8.4
  - dependency-name: github.com/ipfs/go-ipfs-config
    versions:
    - 0.12.0
  - dependency-name: github.com/stretchr/testify
    versions:
    - 1.7.0
