// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: protobuf/tree.models.proto

package models

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ValueWithProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Leaf  *ValueWithProof_Leaf   `protobuf:"bytes,2,opt,name=leaf,proto3" json:"leaf,omitempty"`
	Proof []*ValueWithProof_Item `protobuf:"bytes,3,rep,name=proof,proto3" json:"proof,omitempty"`
}

func (x *ValueWithProof) Reset() {
	*x = ValueWithProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_tree_models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValueWithProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueWithProof) ProtoMessage() {}

func (x *ValueWithProof) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_tree_models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueWithProof.ProtoReflect.Descriptor instead.
func (*ValueWithProof) Descriptor() ([]byte, []int) {
	return file_protobuf_tree_models_proto_rawDescGZIP(), []int{0}
}

func (x *ValueWithProof) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ValueWithProof) GetLeaf() *ValueWithProof_Leaf {
	if x != nil {
		return x.Leaf
	}
	return nil
}

func (x *ValueWithProof) GetProof() []*ValueWithProof_Item {
	if x != nil {
		return x.Proof
	}
	return nil
}

type ValueWithProof_Leaf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ValueHash []byte `protobuf:"bytes,2,opt,name=valueHash,proto3" json:"valueHash,omitempty"`
	Version   uint64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *ValueWithProof_Leaf) Reset() {
	*x = ValueWithProof_Leaf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_tree_models_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValueWithProof_Leaf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueWithProof_Leaf) ProtoMessage() {}

func (x *ValueWithProof_Leaf) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_tree_models_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueWithProof_Leaf.ProtoReflect.Descriptor instead.
func (*ValueWithProof_Leaf) Descriptor() ([]byte, []int) {
	return file_protobuf_tree_models_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ValueWithProof_Leaf) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ValueWithProof_Leaf) GetValueHash() []byte {
	if x != nil {
		return x.ValueHash
	}
	return nil
}

func (x *ValueWithProof_Leaf) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ValueWithProof_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height  uint32 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Size    uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Version uint64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Left    []byte `protobuf:"bytes,4,opt,name=left,proto3" json:"left,omitempty"`
	Right   []byte `protobuf:"bytes,5,opt,name=right,proto3" json:"right,omitempty"`
}

func (x *ValueWithProof_Item) Reset() {
	*x = ValueWithProof_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_tree_models_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValueWithProof_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueWithProof_Item) ProtoMessage() {}

func (x *ValueWithProof_Item) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_tree_models_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueWithProof_Item.ProtoReflect.Descriptor instead.
func (*ValueWithProof_Item) Descriptor() ([]byte, []int) {
	return file_protobuf_tree_models_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ValueWithProof_Item) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ValueWithProof_Item) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ValueWithProof_Item) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ValueWithProof_Item) GetLeft() []byte {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *ValueWithProof_Item) GetRight() []byte {
	if x != nil {
		return x.Right
	}
	return nil
}

var File_protobuf_tree_models_proto protoreflect.FileDescriptor

var file_protobuf_tree_models_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x72, 0x65, 0x65, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x22, 0xd4, 0x02, 0x0a, 0x0e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x57, 0x69,
	0x74, 0x68, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2f, 0x0a,
	0x04, 0x6c, 0x65, 0x61, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x57, 0x69, 0x74, 0x68, 0x50, 0x72,
	0x6f, 0x6f, 0x66, 0x2e, 0x4c, 0x65, 0x61, 0x66, 0x52, 0x04, 0x6c, 0x65, 0x61, 0x66, 0x12, 0x31,
	0x0a, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x57, 0x69, 0x74, 0x68,
	0x50, 0x72, 0x6f, 0x6f, 0x66, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f,
	0x66, 0x1a, 0x50, 0x0a, 0x04, 0x4c, 0x65, 0x61, 0x66, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x1a, 0x76, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protobuf_tree_models_proto_rawDescOnce sync.Once
	file_protobuf_tree_models_proto_rawDescData = file_protobuf_tree_models_proto_rawDesc
)

func file_protobuf_tree_models_proto_rawDescGZIP() []byte {
	file_protobuf_tree_models_proto_rawDescOnce.Do(func() {
		file_protobuf_tree_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_tree_models_proto_rawDescData)
	})
	return file_protobuf_tree_models_proto_rawDescData
}

var file_protobuf_tree_models_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_tree_models_proto_goTypes = []interface{}{
	(*ValueWithProof)(nil),      // 0: models.ValueWithProof
	(*ValueWithProof_Leaf)(nil), // 1: models.ValueWithProof.Leaf
	(*ValueWithProof_Item)(nil), // 2: models.ValueWithProof.Item
}
var file_protobuf_tree_models_proto_depIdxs = []int32{
	1, // 0: models.ValueWithProof.leaf:type_name -> models.ValueWithProof.Leaf
	2, // 1: models.ValueWithProof.proof:type_name -> models.ValueWithProof.Item
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobuf_tree_models_proto_init() }
func file_protobuf_tree_models_proto_init() {
	if File_protobuf_tree_models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_tree_models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValueWithProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_tree_models_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValueWithProof_Leaf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_tree_models_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValueWithProof_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_tree_models_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_tree_models_proto_goTypes,
		DependencyIndexes: file_protobuf_tree_models_proto_depIdxs,
		MessageInfos:      file_protobuf_tree_models_proto_msgTypes,
	}.Build()
	File_protobuf_tree_models_proto = out.File
	file_protobuf_tree_models_proto_rawDesc = nil
	file_protobuf_tree_models_proto_goTypes = nil
	file_protobuf_tree_models_proto_depIdxs = nil
}
